apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: diagnostics-ingress
spec:
  rules:
  - host: diagnostics
    http:
      paths:
      - backend:
          serviceName: diagnostics-service
          servicePort: 80
